CREATE TABLE Building
(
  BuildingName VARCHAR(50) NOT NULL,
  ZIP INT NOT NULL,
  DateOfConstruction DATE NOT NULL,
  PRIMARY KEY (ZIP)
);

CREATE TABLE Elevator
(
  NextTestDate DATE NOT NULL,
  IsOperational VARCHAR(50) NOT NULL,
  ZIP INT NOT NULL,
  PRIMARY KEY (ZIP),
  FOREIGN KEY (ZIP) REFERENCES Building(ZIP)
);

CREATE TABLE Human
(
  ID INT NOT NULL,
  FirstName VARCHAR(50) NOT NULL,
  Gender VARCHAR(50) NOT NULL,
  Age INT NOT NULL,
  Phone VARCHAR(50) NOT NULL,
  Email VARCHAR(50) NOT NULL,
  LastName VARCHAR(50) NOT NULL,
  HomeTown VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE Employee
(
  Tofes101 VARCHAR(50) NOT NULL,
  Salary INT NOT NULL,
  ID INT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID) REFERENCES Human(ID)
);

CREATE TABLE Student
(
  Degree VARCHAR(50) NOT NULL,
  ID INT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID) REFERENCES Human(ID)
);

CREATE TABLE Cleaner
(
  ID INT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID) REFERENCES Employee(ID)
);

CREATE TABLE Engeneer
(
  License VARCHAR(50) NOT NULL,
  ID INT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID) REFERENCES Employee(ID)
);

CREATE TABLE Room
(
  IsNagish VARCHAR(50) NOT NULL,
  RoomID INT NOT NULL,
  Color VARCHAR(50) NOT NULL,
  Password VARCHAR(50) NOT NULL,
  SquareFeet INT NOT NULL,
  ZIP INT NOT NULL,
  CleanerID INT,
  PRIMARY KEY (RoomID, ZIP),
  FOREIGN KEY (ZIP) REFERENCES Building(ZIP),
  FOREIGN KEY (CleanerID) REFERENCES Cleaner(ID)
);

CREATE TABLE AC
(
  Company VARCHAR(50) NOT NULL,
  ModelNum INT NOT NULL,
  RoomID INT NOT NULL,
  ZIP INT NOT NULL,
  PRIMARY KEY (RoomID, ZIP),
  FOREIGN KEY (RoomID, ZIP) REFERENCES Room(RoomID, ZIP)
);

CREATE TABLE Bed
(
  BedNum INT NOT NULL,
  IsTopBunk VARCHAR(50) NOT NULL,
  Cost INT NOT NULL,
  ID INT NOT NULL,
  RoomID INT NOT NULL,
  ZIP INT NOT NULL,
  PRIMARY KEY (RoomID, ZIP, BedNum),
  FOREIGN KEY (ID) REFERENCES Student(ID),
  FOREIGN KEY (RoomID, ZIP) REFERENCES Room(RoomID, ZIP)
);

CREATE TABLE NeedToFix
(
  ZIP INT NOT NULL,
  EngID INT NOT NULL,
  FOREIGN KEY (ZIP) REFERENCES Elevator(ZIP),
  FOREIGN KEY (EngID) REFERENCES Engeneer(ID)
);

CREATE TABLE Rent
(
  EndOfRentDate DATE NOT NULL,
  StudentID INT NOT NULL UNIQUE,
  BedNum INT NOT NULL,
  RoomID INT NOT NULL,
  ZIP INT NOT NULL,
  UNIQUE(BedNum,RoomID,ZIP),
  FOREIGN KEY (StudentID) REFERENCES Student(ID),
  FOREIGN KEY (BedNum, RoomID, ZIP) REFERENCES Bed(BedNum, RoomID, ZIP)
);
